apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: rate-limiting
metadata:
  name: todoapi-rate-limit
config:
  second: 2
  limit_by: consumer
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: response-transformer
metadata:
  name: add-response-header
config:
  add:
    headers:
      - "x-custom-response-header: custom-value"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: request-transformer
metadata:
  name: add-request-header
config:
  add:
    headers:
      - "x-custom-request-header: custom-value"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: key-auth
metadata:
  name: todoapi-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: todo-basic-auth
config:
  hide_credentials: true
plugin: basic-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-ws-customization
upstream:
  # hash_on: header
  # hash_on_header: x-lb
  # hash_fallback: ip
  hash_on: cookie
  hash_on_cookie: "todo-cookie"
  hash_on_cookie_path: "/ws"
  algorithm: consistent-hashing
