name: Todoui Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            todoui:
              - 'todoui/**'
            todoapi:
              - 'todoapi/**'

      - name: Build todoui Using Node.js ${{ matrix.node-version }}
        working-directory: todoui
        if: steps.filter.outputs.todoui == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm ci
          npm run build --if-present
          npm test
